### ISSUE TITLE
sr.ht source disappeared / git tags missing

### ISSUE THREAD

**Issue by fossdd** [renerocksai/aercbook#1]
Hey, I noticed your sr.ht account including  the source for aercbook is missing: https://sr.ht/~renerocksai/aercbook/

Is this intentional? Is this GitHub account the new canonical location for the repository?

If so, I noticied that the git tags in this repository are missing. Could you add them back?

Thanks!

**Comment by renerocksai** [comment]
Hi, yes, it is intentional.

I just pushed the tags, thx for pointing that out :smile:.

**Comment by fossdd** [comment]
Thanks a lot!
